version: "3.8"

services:
  db:
    image: postgres:14-alpine
    container_name: postgresql-ecommerce
    ports:
      - 5444:5432
    volumes:
      - ./db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres_pw
      - POSTGRES_USER=postgres
      - POSTGRES_DB=fiber_ecommerce
    restart: unless-stopped
  
  be-service:
    image: rickyslash/fiber-ecommerce:1.0.0
    container_name: ecommerce-service
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=${DATABESE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - MIDTRANS_SERVER_KEY=${MIDTRANS_SERVER_KEY}
      - ENV=PROD
    restart: always
    depends_on:
      - db